### ISSUE TITLE
Training part

### ISSUE THREAD

**Issue by saisusmitha** [Js2Hou/Swin-CBIR#3]
Kindly let me know to train this. I mean if we want to apply for some other dataset.

**Comment by Js2Hou** [comment]
I just used [swin-Transformer](https://github.com/microsoft/Swin-Transformer)'s pre-training checkpoint, where you can find the training details.

**Comment by NQHuy1905** [comment]
@Js2Hou i see that, but how you tunned for Transformer with custom dataset, like other CNN we will freeze all layers except last layer and fine tuning it, but i don't see that option in their trainning file, how did you do?

**Comment by Js2Hou** [comment]
I didn't fine-tune the model.

**Comment by NQHuy1905** [comment]
But is the model still good if i use that to extract feature with other classes not in ImageNet dataset

**Comment by Js2Hou** [comment]
Yes, swin-transformer has amazing performance
